version: "3"
services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - db-volume:/var/lib/mysql
      - ./db/init.d:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf

  api:
    build: .
    container_name: api
    volumes:
      - ./:/go/src/app
    ports:
      - "8080:8080"
    environment:
      CA_MISSION_DBHOST: db
      CA_MISSION_DBPORT: 3306
      CA_MISSION_DBUSERNAME: root
      CA_MISSION_DBPASSWORD: root
      CA_MISSION_DBNAME: ca_mission
    restart: always
    depends_on:
      - db
volumes:
  db-volume:
