version: "3"
services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init.d:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  go:
    build: .
    container_name: go
    volumes:
      - ./:/go/src/app
    ports:
      - "8080:8080"
