version: "3"
services:
  db:
    build: ./db
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    # command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  go:
    build: .
    container_name: go
    volumes:
      - ./:/go/src/app
    ports:
      - "8080:8080"
