version: "3"
services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - db-volume:/var/lib/mysql
      - ./db/init.d:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf

  go:
    build: .
    container_name: go
    volumes:
      - ./:/go/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  db-volume:
