version: "3"
services:
  db:
    build: ./db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root-pass
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    # volumes:
    #   - ./db/init:/docker-entrypoint-initdb.d
  go: # service名
    build: ./go # ビルドに使用するDockerfileがあるディレクトリ指定
    container_name: go
    volumes:
      - ./go/:/go/src/app
    ports:
      - "8080:8080"
